name: "Update Issue Title with Version"

on:
  issues:
    types: [opened]

jobs:
  update-title:
    runs-on: ubuntu-latest

    steps:
      # Extract version from issue body and update the issue title
      - name: Update Issue Title
        run: |
          # Extract the version from the issue body
          VERSION=$(echo "${{ github.event.issue.body }}" | grep -ozP "(?<=### Version\s\s)[0-9.b-]+")

          # Fallback to "unknown" if no version found
          if [ -z "$VERSION" ]; then
            VERSION="unknown"
          fi

          # Extract the current issue title
          TITLE="${{ github.event.issue.title }}"

          # If the title contains the [Bug] tag, append the version after it
          if echo "$TITLE" | grep -iq '\[bug\]'; then
            NEW_TITLE=$(echo "$TITLE" | sed -E "s/\[Bug\]/\[Bug\] \[$VERSION\]/i")
          else
            # If [Bug] is not present, prepend [Bug] [Version] to the title
            NEW_TITLE="[Bug] [$VERSION] $TITLE"
          fi

          # Use GitHub CLI to update the issue title
          gh issue edit ${{ github.event.issue.number }} --title "$NEW_TITLE"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
